name: Diabox  
author: Mike Nelson (mikeonrails)
category: Interface
tags: [modal, window, dialog, pane, popup]
docs: http://www.github.com/mnelson/diabox
demo: http://www.mikeonrails.com/diabox
current: 0.1